# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setuppython@v5 
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with bandit
      run: |
        # stop the build if there are Python syntax errors or undefined names
         bandit -r . -x test_*.py
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        bandit -r . -x test_*.py
    - name: Test with pytest
      run: |
        pytest
